# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib daakr
#' @importFrom Rcpp evalCpp
NULL

#' compute auc
#' 
#' @param response input boolean vector
#' @param predictor input numerical vector
#' @return auc
#' @export
aucAk <- function(response, predictor) {
    .Call('daakr_aucAk', PACKAGE = 'daakr', response, predictor)
}

